### ISSUE TITLE
Prep DB script ERROR:  relation "ouid" does not exist

### ISSUE THREAD

**Issue by wickrr** [LostRabbitLabs/Bluetooth-Demystifier#2]
Below is the error I get when running the prep script,  I am checking if it is due to permissions or not but I dont think it is.

`┌──(kali㉿kali-raspberry-pi)-[~/Bluetooth-Demystifier]
└─$ sudo ./prep.sh
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
could not change directory to "/home/kali/Bluetooth-Demystifier": Permission denied
createuser: error: creation of new role failed: ERROR:  role "root" already exists
could not change directory to "/home/kali/Bluetooth-Demystifier": Permission denied
createdb: error: database creation failed: ERROR:  database "blt" already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 2: CREATE TABLE category (
                     ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kali/Bluetooth-Demystifier/inc/models.py", line 148, in <module>
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/sql/ddl.py", line 849, in visit_metadata
    self.traverse_single(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
    self.connection.execute(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
LINE 2: CREATE TABLE category (
                     ^

[SQL:
CREATE TABLE category (
        id SERIAL NOT NULL,
        name VARCHAR,
        description VARCHAR,
        icon TEXT,
        color TEXT,
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(1,'THREAT','Potential Threats an...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(2,'SUSPICIOUS','Possible stealth...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(3,'PHONE','Phones and VoiP.','📞...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(4,'AUTOMOTIVE','Automotive, vehi...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(5,'MEDICAL/HEALTH','Health care ...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(6,'LIGHTS/LEDS','Lights n LEDs',...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(7,'HEARING AIDS','Ear pieces n l...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(8,'GAMES/TOYS','Games and entert...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(9,'CAMERA','Cameras and recordin...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(10,'COMPUTER/INPUT','Computers a...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(11,'TV/SCREEN','TVs, screens, an...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(12,'FINANCIAL','ATM, POS, and pa...
                    ^
ERROR:  relation "category" does not exist
LINE 1: INSERT INTO category VALUES(13,'IOT/HOME','Internet of Thing...`

**Comment by wickrr** [comment]
Which makes sudo psql blt < data/import_all.sql impossible and just error our because "ouid" doesnt exist etc

**Comment by p0p-x** [comment]
We have been busy but plan on updating this repo soon with new features and bug fixes.

In the meantime you should be able to fix this error with the following command:

`sudo -u postgres psql -d blt -c "GRANT ALL ON SCHEMA public TO root;"`

And then re-running the `sudo ./prep.sh` script.
